### Tutti gli allenatori
GET http://localhost:8000/api/allenatori

### Singolo allenatore
GET http://localhost:8000/api/allenatore/1

### Tutti i giocatori
GET http://localhost:8000/api/giocatori/estratti

### Singolo giocatore
GET http://localhost:8000/api/giocatore/4

### Estrai giocatore
POST http://localhost:8000/api/estrai
Content-Type: application/json

{
    "id_giocatore": 4
}

### Riponi giocatore
POST http://localhost:8000/api/riponi
Content-Type: application/json

{
    "id_giocatore": 4
}

### Acquista giocatore
POST http://localhost:8000/api/acquista
Content-Type: application/json

{
    "id_giocatore": 4,
    "id_allenatore": 1,
    "prezzo": 100
}